version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 529088268162.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=529088268162.dkr.ecr.ap-southeast-1.amazonaws.com/betterwellness/user-service
      - IMAGE_TAG=latest
      - aws eks update-kubeconfig --region ap-southeast-1 --name betterwellness-cluster

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t betterwellness/user-service .
      - docker tag betterwellness/user-service:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Restarting Kubernetes deployment...
      - kubectl rollout restart deployment betterwellness-user -n betterwellness-cluster
