version: 0.2
phases:
  
  pre_build:
    commands:
      - echo "🔐 Logging in to ECR..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 565106043125.dkr.ecr.ap-southeast-1.amazonaws.com
      - aws eks update-kubeconfig --region ap-southeast-1 --name betterwellness-cluster
      - export REPOSITORY_URI=565106043125.dkr.ecr.ap-southeast-1.amazonaws.com/betterwellness/user-service
      - export IMAGE_TAG=latest
  build:
    commands:
      - echo "🏗️ Building Docker image..."
      - docker build -t betterwellness/user-service .
      - docker tag betterwellness/user-service:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "📤 Pushing image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "📤 Pushing image complete"
      - echo "✅ Restarting deployment user-service..."
      - kubectl rollout restart deployment betterwellness-user